
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOL_TYPE CHAR_TYPE FLOAT_TYPE IDENTIFIER INT_TYPE SEMICOLON STRING_TYPEstatement : variable_declaration SEMICOLONvariable_declaration : type IDENTIFIERtype : INT_TYPE\n            | FLOAT_TYPE\n            | STRING_TYPE\n            | BOOL_TYPE\n            | CHAR_TYPE\n    '
    
_lr_action_items = {'INT_TYPE':([0,],[4,]),'FLOAT_TYPE':([0,],[5,]),'STRING_TYPE':([0,],[6,]),'BOOL_TYPE':([0,],[7,]),'CHAR_TYPE':([0,],[8,]),'$end':([1,9,],[0,-1,]),'SEMICOLON':([2,10,],[9,-2,]),'IDENTIFIER':([3,4,5,6,7,8,],[10,-3,-4,-5,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'variable_declaration':([0,],[2,]),'type':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> variable_declaration SEMICOLON','statement',2,'p_statement','parser.py',35),
  ('variable_declaration -> type IDENTIFIER','variable_declaration',2,'p_variable_declaration','parser.py',40),
  ('type -> INT_TYPE','type',1,'p_type','parser.py',44),
  ('type -> FLOAT_TYPE','type',1,'p_type','parser.py',45),
  ('type -> STRING_TYPE','type',1,'p_type','parser.py',46),
  ('type -> BOOL_TYPE','type',1,'p_type','parser.py',47),
  ('type -> CHAR_TYPE','type',1,'p_type','parser.py',48),
]
